#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// 啟用 Classic BT
#define ENABLE_CLASSIC 1

// 啟用 BLE
#define ENABLE_BLE 1

// 啟用 HID Host
#define ENABLE_HID_HOST 1

// Link key 儲存數量
#define NVM_NUM_LINK_KEYS 16

// 啟用 L2CAP
#define ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE 1

// 其他必要設定
#define HCI_ACL_PAYLOAD_SIZE 1024
#define MAX_NR_CONNECTIONS 4
#define MAX_NR_HCI_CONNECTIONS 4
#define MAX_NR_L2CAP_SERVICES 4
#define MAX_NR_L2CAP_CHANNELS 4
#define MAX_NR_RFCOMM_MULTIPLEXERS 1
#define MAX_NR_RFCOMM_SERVICES 1
#define MAX_NR_RFCOMM_CHANNELS 1
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 4
#define MAX_NR_WHITELIST_ENTRIES 4
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_SERVICE_RECORD_ITEMS 4
#define MAX_NR_HID_HOST_CONNECTIONS 2

// BTstack 設定
#define BTSTACK_FILE__ __FILE__
#define HAVE_BTSTACK_STDIN

#endif // BTSTACK_CONFIG_H
